# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'emackie9'
    reviewers:
      - 'emackie9'
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    assignees:
      - 'emackie9'
    reviewers:
      - 'emackie9'
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
    groups:
      jest:
        patterns:
          - '@types/jest'
          - 'jest'
      nestjs:
        patterns:
          - '@nestjs/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
